name: flutter_food_app
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  splashscreen: ^1.3.5
  flutter_svg: ^0.19.3
  flutter_rating_bar: ^4.0.0
  # flutter_staggered_animations: ^0.1.2
  # auto_animated: ^2.1.0
  custom_switch: ^0.0.1
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  image_picker: ^0.7.2
  firebase_storage: ^8.0.0 
  provider: ^5.0.0
  cloud_firestore: ^1.0.0
  uuid: ^3.0.1
  path: ^1.6.4
  firebase_crashlytics: ^1.0.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: FlutterIcons
      fonts:
        - asset: images/fonts/FlutterIcons.ttf
